# Optional Lab: Python, NumPy and Vectorization
A brief introduction to some of the scientific computing used in this course. In particular the NumPy scientific computing package and its use with python.

# Outline
- [&nbsp;&nbsp;1.1 Goals](#toc_40015_1.1)
- [&nbsp;&nbsp;1.2 Useful References](#toc_40015_1.2)
- [2 Python and NumPy <a name='Python and NumPy'></a>](#toc_40015_2)
- [3 Vectors](#toc_40015_3)
- [&nbsp;&nbsp;3.1 Abstract](#toc_40015_3.1)
- [&nbsp;&nbsp;3.2 NumPy Arrays](#toc_40015_3.2)
- [&nbsp;&nbsp;3.3 Vector Creation](#toc_40015_3.3)
- [&nbsp;&nbsp;3.4 Operations on Vectors](#toc_40015_3.4)
- [4 Matrices](#toc_40015_4)
- [&nbsp;&nbsp;4.1 Abstract](#toc_40015_4.1)
- [&nbsp;&nbsp;4.2 NumPy Arrays](#toc_40015_4.2)
- [&nbsp;&nbsp;4.3 Matrix Creation](#toc_40015_4.3)
- [&nbsp;&nbsp;4.4 Operations on Matrices](#toc_40015_4.4)


In [1]:
# importing numpy library and time module
import numpy as np    # it is an unofficial standard to use np for numpy
import time

<a name="toc_40015_1.1"></a>
## 1.1 Goals
In this lab, you will:
- Review the features of NumPy and Python that are used in Course 1

<a name="toc_40015_1.2"></a>
## 1.2 Useful References
- NumPy Documentation including a basic introduction: [NumPy.org](https://NumPy.org/doc/stable/)
- A challenging feature topic: [NumPy Broadcasting](https://NumPy.org/doc/stable/user/basics.broadcasting.html)


<a name="toc_40015_2"></a>
# 2 Python and NumPy <a name='Python and NumPy'></a>
Python is the programming language we will be using in this course. It has a set of numeric data types and arithmetic operations. NumPy is a library that extends the base capabilities of python to add a richer data set including more numeric types, vectors, matrices, and many matrix functions. NumPy and python  work together fairly seamlessly. Python arithmetic operators work on NumPy data types and many NumPy functions will accept python data types.


<a name="toc_40015_3"></a>
# 3 Vectors
<a name="toc_40015_3.1"></a>
## 3.1 Abstract
<img align="right" src="./images/C1_W2_Lab04_Vectors.PNG" style="width:340px;" >Vectors, as you will use them in this course, are ordered arrays of numbers. In notation, vectors are denoted with lower case bold letters such as $\mathbf{x}$.  The elements of a vector are all the same type. A vector does not, for example, contain both characters and numbers. The number of elements in the array is often referred to as the *dimension* though mathematicians may prefer *rank*. The vector shown has a dimension of $n$. The elements of a vector can be referenced with an index. In math settings, indexes typically run from 1 to n. In computer science and these labs, indexing will typically run from 0 to n-1.  In notation, elements of a vector, when referenced individually will indicate the index in a subscript, for example, the $0^{th}$ element, of the vector $\mathbf{x}$ is $x_0$. Note, the x is not bold in this case.  


**Notes:**

Dimension: Number of elements in vector, or "Rank".

$n$: Vector has a dimension of $n$.

Elements of a vector can be referenced by index like an array. In math 1..n, but in Code 0...n-1

$x_{0}$: indicates the first element $0^{th}$ element of vector or first element in Code.

<a name="toc_40015_3.2"></a>
## 3.2 NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). Right away, you may notice we have overloaded the term 'dimension'. Above, it was the number of elements in the vector, here, dimension refers to the number of indexes of an array. A one-dimensional or 1-D array has one index. In Course 1, we will represent vectors as NumPy 1-D arrays. 

 - 1-D array, shape (n,): n elements indexed [0] through [n-1]
 

**Notes:**

`dtype`: ndimensional array containing elements of same type, and it's NumPy basic data structure which is indexable.

Dimension: number of indexes in an array, and 1D arrays has one index vector[j]

1-D array: shape(n,): n elements indexed [0] through [n-1]

<a name="toc_40015_3.3"></a>
## 3.3 Vector Creation


Data creation routines in NumPy will generally have a first parameter which is the shape of the object. This can either be a single value for a 1-D result or a tuple (n,m,...) specifying the shape of the result. Below are examples of creating vectors using these routines.

In [17]:
# NumPy routines which allocate memory and fill arrays with value

# create 1D array of 4 elements and fill with zeros. The data type by default is float
# parameter is int and with 4 elements
a = np.zeros(4);
print(f"np.zeros(4) :   a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


# same as before but the parameter is tuple (4,), and with 4 elements and it is 0D.
# tuple of (4,1) will result in
# [[0.][0.][0.][0.]]
# tuple of (4,2) will result in
# [[0. 0.][0. 0.][0. 0.][0. 0.]]
a = np.zeros((4,));
print(f"np.zeros(4,) :  a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


# will create random sample 1D array of size 4
# I can also pass tuple like before and it will result the same shape
a = np.random.random_sample(4);
print(f"np.random.random_sample(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.zeros(4) :   a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.zeros(4,) :  a = [0. 0. 0. 0.], a shape = (4,), a data type = float64
np.random.random_sample(4): a = [0.3437151  0.00135934 0.35341428 0.56553984], a shape = (4,), a data type = float64


Some data creation routines do not take a shape tuple:

In [29]:
# NumPy routines which allocate memory and fill arrays with value but do not accept shape as input argument

# will create a numpy 1D array with np.arange(), but it will not take shape but increment from 0 till parameter -1
# 4. will make the data type float, and create from 0 till 3
a = np.arange(4.);
print(f"np.arange(4.):     a = {a}, a shape = {a.shape}, a data type = {a.dtype}")


# will create a random numpy 1D array of 4 elements
# the randomness in this method is different
a = np.random.rand(4);
print(f"np.random.rand(4): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.arange(4.):     a = [0. 1. 2. 3.], a shape = (4,), a data type = float64
np.random.rand(4): a = [0.54144797 0.79728387 0.78530556 0.9519948 ], a shape = (4,), a data type = float64


values can be specified manually as well. 

In [31]:
# NumPy routines which allocate memory and fill with user specified values

# creating numpy arrays by specifying the elements manually of int type
a = np.array([5,4,3,2]);
print(f"np.array([5,4,3,2]):  a = {a},     a shape = {a.shape}, a data type = {a.dtype}")


# creating numpy arrays by specifying the elements manually of float type
a = np.array([5.,4,3,2]);
print(f"np.array([5.,4,3,2]): a = {a}, a shape = {a.shape}, a data type = {a.dtype}")

np.array([5,4,3,2]):  a = [5 4 3 2],     a shape = (4,), a data type = int64
np.array([5.,4,3,2]): a = [5. 4. 3. 2.], a shape = (4,), a data type = float64


These have all created a one-dimensional vector  `a` with four elements. `a.shape` returns the dimensions. Here we see a.shape = `(4,)` indicating a 1-d array with 4 elements.  

<a name="toc_40015_3.4"></a>
## 3.4 Operations on Vectors
Let's explore some operations using vectors.
<a name="toc_40015_3.4.1"></a>
### 3.4.1 Indexing
Elements of vectors can be accessed via indexing and slicing. NumPy provides a very complete set of indexing and slicing capabilities. We will explore only the basics needed for the course here. Reference [Slicing and Indexing](https://NumPy.org/doc/stable/reference/arrays.indexing.html) for more details.  
**Indexing** means referring to *an element* of an array by its position within the array.  
**Slicing** means getting a *subset* of elements from an array based on their indices.  
NumPy starts indexing at zero so the 3rd element of an vector $\mathbf{a}$ is `a[2]`.

In [33]:
#vector indexing operations on 1-D vectors
# will create numpy 1D starting from 0 till 9 of type int
a = np.arange(10)
# [0 1 2 3 4 5 6 7 8 9]
print(a)

#access an element
# the shape will be () because it is a scalar
# 
print(f"a[2].shape: {a[2].shape} a[2]  = {a[2]}, Accessing an element returns a scalar")

# access the last element, negative indexes count from the end
# a[-1] = a[9] = 9
print(f"a[-1] = {a[-1]}")

#indexs must be within the range of the vector or they will produce and error
try:
    # out of bound and 10 does not exist
    c = a[10]
except Exception as e:
    print("The error message you'll see is:")
    print(e)

[0 1 2 3 4 5 6 7 8 9]
a[2].shape: () a[2]  = 2, Accessing an element returns a scalar
a[-1] = 9
The error message you'll see is:
index 10 is out of bounds for axis 0 with size 10


<a name="toc_40015_3.4.2"></a>
### 3.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [39]:
#vector slicing operations

# will create numpy 1D starting from 0 till 9 of type int
# [0 1 2 3 4 5 6 7 8 9]
a = np.arange(10)
print(f"a         = {a}")


# access 5 consecutive elements (start:stop:step)
# [2 3 4 5 6]
# start= 2 will start from 2
# stop=7 will stop at 7th element of original
# step=1 will take elements consecutively
c = a[2:7:1];     print("a[2:7:1] = ", c)


# access 3 elements separated by two 
# [2 4 6]
# start= 2 will start from 2
# stop= 7 will stop at 7th element of original
# step= 2 will skip 1 element
c = a[2:7:2];     print("a[2:7:2] = ", c)


# access all elements index 3 and above
# [3 4 5 6 7 8 9]
# start= 2 will start from 3rd element till the end
# end= null
c = a[3:];        print("a[3:]    = ", c)



# access all elements below index 3
# [0 1 2]
# will stop at 3rd element of original 
# start= null
# end= 3
c = a[:3];        print("a[:3]    = ", c)


# access all elements
# start= null
# end= null
c = a[:];         print("a[:]     = ", c)


# access all elements
# start= null
# end= null
# step= 3 will take every 3rd element
c = a[::3];         print("a[::3]     = ", c)

a         = [0 1 2 3 4 5 6 7 8 9]
a[2:7:1] =  [2 3 4 5 6]
a[2:7:2] =  [2 4 6]
a[3:]    =  [3 4 5 6 7 8 9]
a[:3]    =  [0 1 2]
a[:]     =  [0 1 2 3 4 5 6 7 8 9]
a[::3]     =  [0 3 6 9]


<a name="toc_40015_3.4.3"></a>
### 3.4.3 Single vector operations
There are a number of useful operations that involve operations on a single vector.

In [45]:
# creates a numpy array manually of type int
a = np.array([1,2,3,4])
print(f"a             : {a}")


# negate elements of a
# which means convert the original numpy array to negatives
# multiply original array with -1
b = -a 
print(f"b = -a        : {b}")


# sum all elements of a, returns a scalar
# add all the number of original array
b = np.sum(a) 
print(f"b = np.sum(a) : {b}")


# find the mean of the original array
b = np.mean(a)
print(f"b = np.mean(a): {b}")


# take the original numpy array and take the square of each elements ^2
b = a**2
print(f"b = a**2      : {b}")


# find the stddev of the original array
b = np.std(a)
print(f"b = np.std(a): {b}")


# find the average of the original array
b = np.average(a)
print(f"b = np.average(a): {b}")

a             : [1 2 3 4]
b = -a        : [-1 -2 -3 -4]
b = np.sum(a) : 10
b = np.mean(a): 2.5
b = a**2      : [ 1  4  9 16]
b = np.std(a): 1.118033988749895
b = np.average(a): 2.5


<a name="toc_40015_3.4.4"></a>
### 3.4.4 Vector Vector element-wise operations
Most of the NumPy arithmetic, logical and comparison operations apply to vectors as well. These operators work on an element-by-element basis. For example 
$$ c_i = a_i + b_i $$

In [51]:
# declaring 2 numpy arrays a, b manually
a = np.array([ 1, 2, 3, 4])
b = np.array([-1,-2, 3, 4])

# this will add the elements one by one
# but they must be of the same size
print(f"Binary operators work element wise: {a + b}")

Binary operators work element wise: [0 0 6 8]


Of course, for this to work correctly, the vectors must be of the same size:

In [53]:
# try a mismatched vector operation
c = np.array([1, 2])

# a size is 4
# b size is 2
# so it will not work because of the different shape
try:
    d = a + c
except Exception as e:
    print("The error message you'll see is:")
    print(e)

The error message you'll see is:
operands could not be broadcast together with shapes (4,) (2,) 


<a name="toc_40015_3.4.5"></a>
### 3.4.5 Scalar Vector operations
Vectors can be 'scaled' by scalar values. A scalar value is just a number. The scalar multiplies all the elements of the vector.

In [63]:
# declaring 1D numpy array
a = np.array([1, 2, 3, 4])

# multiply a by a scalar (number)
b = 5 * a
print(f"b = 5 * a : {b}")

# divide a by a scalar (number)
b = a / 4
print(f"b = a/4 : {b}")

b = 5 * a : [ 5 10 15 20]
b = a/4 : [0.25 0.5  0.75 1.  ]


<a name="toc_40015_3.4.6"></a>
### 3.4.6 Vector Vector dot product
The dot product is a mainstay of Linear Algebra and NumPy. This is an operation used extensively in this course and should be well understood. The dot product is shown below.

<img src="./images/C1_W2_Lab04_dot_notrans.gif" width=800> 

The dot product multiplies the values in two vectors element-wise and then sums the result.
Vector dot product requires the dimensions of the two vectors to be the same. 

Let's implement our own version of the dot product below:

**Using a for loop**, implement a function which returns the dot product of two vectors. The function to return given inputs $a$ and $b$:
$$ x = \sum_{i=0}^{n-1} a_i b_i $$
Assume both `a` and `b` are the same shape.

In [74]:
def my_dot(a, b): 
    """
   Compute the dot product of two vectors
 
    Args:
      a (ndarray (n,)):  input vector 
      b (ndarray (n,)):  input vector with same dimension as a
    
    Returns:
      x (scalar): 
    """
    
    # will store the summation result and will be scalar/number 
    x=0
    
    # can only be used if it is np array
    # a.shape[0]

    # for python arrays
    # len(a))

    for i in range(a.shape[0]):
        x = x + a[i] * b[i]
    return x

In [75]:
# test 1-D

# declaring 2 1D numpy array
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

# will call the my_dot function with two np arrays
print(f"my_dot(a, b) = {my_dot(a, b)}")

my_dot(a, b) = 24


Note, the dot product is expected to return a scalar value. 

Let's try the same operations using `np.dot`.  

In [77]:
# test 1-D

# declaring 2 1D numpy array
a = np.array([1, 2, 3, 4])
b = np.array([-1, 4, 3, 2])

# computing the dot product with numpy array
c = np.dot(a, b)
print(f"NumPy 1-D np.dot(a, b) = {c}, np.dot(a, b).shape = {c.shape} ") 

# changing the order (same result)
c = np.dot(b, a)
print(f"NumPy 1-D np.dot(b, a) = {c}, np.dot(a, b).shape = {c.shape} ")


NumPy 1-D np.dot(a, b) = 24, np.dot(a, b).shape = () 
NumPy 1-D np.dot(b, a) = 24, np.dot(a, b).shape = () 


Above, you will note that the results for 1-D matched our implementation.

<a name="toc_40015_3.4.7"></a>
### 3.4.7 The Need for Speed: vector vs for loop
We utilized the NumPy  library because it improves speed memory efficiency. Let's demonstrate:

In [80]:
# configuring the randomness
np.random.seed(1)

# declaring 2 1D numpy array with shape of 10000000
a = np.random.rand(10000000)  # very large arrays
b = np.random.rand(10000000)


# computing the timing of numpy dot function/ vectorized
start_time = time.time()  # capture start time
c = np.dot(a, b)
end_time = time.time()  # capture end time

# will print the result and show the timing * 1000 to convert to ms
print(f"np.dot(a, b) =  {c:.4f}")
print(f"Vectorized version duration: {1000*(end_time-start_time):.4f} ms ")


# computing the timing of loop function / not vectorized
start_time = time.time()  # capture start time
c = my_dot(a,b)
end_time = time.time()  # capture end time

# will print the result and show the timing * 1000 to convert to ms
print(f"my_dot(a, b) =  {c:.4f}")
print(f"loop version duration: {1000*(end_time-start_time):.4f} ms ")


#remove these big arrays from memory
del(a);
del(b);

np.dot(a, b) =  2501072.5817
Vectorized version duration: 13.6561 ms 
my_dot(a, b) =  2501072.5817
loop version duration: 2473.3341 ms 


So, vectorization provides a large speed up in this example. This is because NumPy makes better use of available data parallelism in the underlying hardware. GPU's and modern CPU's implement Single Instruction, Multiple Data (SIMD) pipelines allowing multiple operations to be issued in parallel. This is critical in Machine Learning where the data sets are often very large.

<a name="toc_12345_3.4.8"></a>
### 3.4.8 Vector Vector operations in Course 1
Vector Vector operations will appear frequently in course 1. Here is why:
- Going forward, our examples will be stored in an array, `X_train` of dimension (m,n). This will be explained more in context, but here it is important to note it is a 2 Dimensional array or matrix (see next section on matrices).
- `w` will be a 1-dimensional vector of shape (n,).
- we will perform operations by looping through the examples, extracting each example to work on individually by indexing X. For example:`X[i]`
- `X[i]` returns a value of shape (n,), a 1-dimensional vector. Consequently, operations involving `X[i]` are often vector-vector.  

That is a somewhat lengthy explanation, but aligning and understanding the shapes of your operands is important when performing vector operations.

In [90]:
# show common Course 1 example

# declaring 2D numpy array with 4 elements and each contains 1 ===> so 4 rows and 1 column ==> X[4][1]
# represents 1 example with set of features
X = np.array([[1],[2],[3],[4]])


# declaring 1D numpy arrary
# represents 1 weight
w = np.array([2])

# computing the dot product of feature 1 * weight 1
# [2] * [2]
c = np.dot(X[1], w)

# [2] * [2] = 4 scalar
print(f"c= {c}")

# 1D Numpy array cuz it is inside 2D of X
print(f"X[1] is {X[1]}")

# 2D Numpy array X[4][1]
print(f"X has shape {X.shape}")

# 1D numpy array
print(f"X[1] has shape {X[1].shape}")

# 1D numpy array
print(f"w has shape {w.shape}")

# scalar
print(f"c has shape {c.shape}")

c= 4
X[1] is [2]
X has shape (4, 1)
X[1] has shape (1,)
w has shape (1,)
c has shape ()


<a name="toc_40015_4"></a>
# 4 Matrices


<a name="toc_40015_4.1"></a>
## 4.1 Abstract
Matrices, are two dimensional arrays. The elements of a matrix are all of the same type. In notation, matrices are denoted with capitol, bold letter such as $\mathbf{X}$. In this and other labs, `m` is often the number of rows and `n` the number of columns. The elements of a matrix can be referenced with a two dimensional index. In math settings, numbers in the index typically run from 1 to n. In computer science and these labs, indexing will run from 0 to n-1.  
<figure>
    <center> <img src="./images/C1_W2_Lab04_Matrices.PNG"  alt='missing'  width=900><center/>
    <figcaption> Generic Matrix Notation, 1st index is row, 2nd is column </figcaption>
<figure/>

$X$: Capital letter means it is a Matrix
$m$: number of rows
$n$: number of columns

To reference a matrix elements ==> X[m][n]

- In Code, indices will be 0 to n-1
- In Maths, indices will be 1 to n

<a name="toc_40015_4.2"></a>
## 4.2 NumPy Arrays

NumPy's basic data structure is an indexable, n-dimensional *array* containing elements of the same type (`dtype`). These were described earlier. Matrices have a two-dimensional (2-D) index [m,n].

In Course 1, 2-D matrices are used to hold training data. Training data is $m$ examples by $n$ features creating an (m,n) array. Course 1 does not do operations directly on matrices but typically extracts an example as a vector and operates on that. Below you will review: 
- data creation
- slicing and indexing

Training Data it can be represented as matrix with the following:

- X[m][n]
- X[rows][columns]
- X[examples][features]

<a name="toc_40015_4.3"></a>
## 4.3 Matrix Creation
The same functions that created 1-D vectors will create 2-D or n-D arrays. Here are some examples


Below, the shape tuple is provided to achieve a 2-D result. Notice how NumPy uses brackets to denote each dimension. Notice further than NumPy, when printing, will print one row per line.


In [92]:
# will create 1D numpy array of zeroes with shape (1,5) ==> a[1][5] ==> a[rows][cols] ==> [0. 0. 0. 0. 0.]
a = np.zeros((1, 5))                                       
print(f"a shape = {a.shape}, a = {a}")                     

# will create 2D numpy array of zeroes with shape (2,1) ==> a[2][1] ==> a[rows][cols] ==> [[0.]
#                                                                                           [0.]]
a = np.zeros((2, 1))                                                                   
print(f"a shape = {a.shape}, a = {a}") 

# will create 1D numpy array of random numbers with shape (1,1) ==> a[1][1] ==> a[rows][cols] ==> [[random]]
a = np.random.random_sample((1, 1))  
print(f"a shape = {a.shape}, a = {a}") 

a shape = (1, 5), a = [[0. 0. 0. 0. 0.]]
a shape = (2, 1), a = [[0.]
 [0.]]
a shape = (1, 1), a = [[0.04997798]]


One can also manually specify data. Dimensions are specified with additional brackets matching the format in the printing above.

In [102]:
# NumPy routines which allocate memory and fill with user specified values

# will create 2D numpy array manually with shape (3,1) ==> a[3][1] ==> a[rows][cols] ==> [[0.
#                                                                                          [4]
#                                                                                          [3]]
# it means that adding 3D into 1D/np.array ==> a[3][1] ==> a[rows][cols]
a = np.array([[5], [4], [3]]);
print(f" a shape = {a.shape}, np.array: a = {a}")


# this to make it more organized
a = np.array([[5],   # One can also
              [4],   # separate values
              [3]]); # into separate rows
print(f" a shape = {a.shape}, np.array: a = {a}")

 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]
 a shape = (3, 1), np.array: a = [[5]
 [4]
 [3]]


<a name="toc_40015_4.4"></a>
## 4.4 Operations on Matrices
Let's explore some operations using matrices.

<a name="toc_40015_4.4.1"></a>
### 4.4.1 Indexing


Matrices include a second index. The two indexes describe [row, column]. Access can either return an element or a row/column. See below:

In [122]:
#vector indexing operations on matrices

# np.arange(6) will create numpy 1D array [0 1 2 3 4 5]
# .reshape will convert 1D array into Matrix 
# paramerter is the new shape
# -1 means it will get from the matrix length
# 2 means 2 column

# can also use this (3 rows, 2 columns)
# a = np.arange(6).reshape(3, 2)
a = np.arange(6).reshape(-1, 2)   #reshape is a convenient way to create matrices
print(f"a.shape: {a.shape}, \na= {a}")

# access an element a[2,0] == a[2][0] a[row_2][col_0]
# shape () = scalar
# type of a[2,0] = int
print(f"\na[2,0].shape: {a[2, 0].shape}, a[2,0] = {a[2, 0]},    type(a[2,0]) = {type(a[2, 0])} Accessing an element returns a scalar\n")

# access a row a[2] == a[row_2]
# shape (2,) cuz elements are scalar
# type of a[2] = a[row_2] = ndarray
print(f"a[2].shape: {a[2].shape}, a[2] = {a[2]},    type(a[2])   = {type(a[2])}")

a.shape: (3, 2), 
a= [[0 1]
 [2 3]
 [4 5]]

a[2,0].shape: (), a[2,0] = 4,    type(a[2,0]) = <class 'numpy.int64'> Accessing an element returns a scalar

a[2].shape: (2,), a[2] = [4 5],    type(a[2])   = <class 'numpy.ndarray'>


It is worth drawing attention to the last example. Accessing a matrix by just specifying the row will return a *1-D vector*.

**Reshape**  
The previous example used [reshape](https://numpy.org/doc/stable/reference/generated/numpy.reshape.html) to shape the array.  
`a = np.arange(6).reshape(-1, 2) `   
This line of code first created a *1-D Vector* of six elements. It then reshaped that vector into a *2-D* array using the reshape command. This could have been written:  
`a = np.arange(6).reshape(3, 2) `  
To arrive at the same 3 row, 2 column array.
The -1 argument tells the routine to compute the number of rows given the size of the array and the number of columns.


<a name="toc_40015_4.4.2"></a>
### 4.4.2 Slicing
Slicing creates an array of indices using a set of three values (`start:stop:step`). A subset of values is also valid. Its use is best explained by example:

In [134]:
#vector 2-D slicing operations

# np.arange(20) create 1D numpy array [0 1 ... 19]
# .reshape(-1, 10) convert to matrix with rows of array size and 10 columns
# can also use
# a = np.arange(20).reshape(2, 10)
a = np.arange(20).reshape(-1, 10)
print(f"a = \n{a}")


# access 5 consecutive elements (start:stop:step)
# a[0, 2:7:1] ==> a[row_1, columns from [2 till 7-1: step =1] ==> shape 6-2+1 = (5,) 1D 1 row - 5 columns 
print("\na[0, 2:7:1] = ", a[0, 2:7:1], ",  a[0, 2:7:1].shape =", a[0, 2:7:1].shape, "a 1-D array")


# access 5 consecutive elements (start:stop:step) in two rows
# a[:, 2:7:1] ==> a[all_rows, columns from [2 till 7-1: step =1] ==> shape 6-2+1 = (5,)  2D 2 rows - 5 columns 
print("\na[:, 2:7:1] = \n", a[:, 2:7:1], ",  a[:, 2:7:1].shape =", a[:, 2:7:1].shape, "a 2-D array")


# access all elements
# a[:, :] ==> a[all_rows, all_columns] ==> shape = (2,10)  2D 2 rows - 10 columns 
print("\na[:,:] = \n", a[:,:], ",  a[:,:].shape =", a[:,:].shape)


# access all elements in one row (very common usage)
# a[1, :] ==> a[row_1, all_columns] ==> shape = (10,) so 10 elements, 1D 1 row - 10 columns/features
# useful to take one training example!!
print("\na[1,:] = ", a[1,:], ",  a[1,:].shape =", a[1,:].shape, "a 1-D array")


# same as
# a[1] = which take one row a which is 1 single training example with 10 features
print("\na[1] = ", a[1],   ",  a[1].shape   =", a[1].shape, "a 1-D array")


a = 
[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]

a[0, 2:7:1] =  [2 3 4 5 6] ,  a[0, 2:7:1].shape = (5,) a 1-D array

a[:, 2:7:1] = 
 [[ 2  3  4  5  6]
 [12 13 14 15 16]] ,  a[:, 2:7:1].shape = (2, 5) a 2-D array

a[:,:] = 
 [[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]] ,  a[:,:].shape = (2, 10)

a[1,:] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1,:].shape = (10,) a 1-D array

a[1] =  [10 11 12 13 14 15 16 17 18 19] ,  a[1].shape   = (10,) a 1-D array


<a name="toc_40015_5.0"></a>
## Congratulations!
In this lab you mastered the features of Python and NumPy that are needed for Course 1.